version: '3.8'

services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: postgres_bus_db
    environment:
      - 'POSTGRES_DB=ProyectoFinalBD'
      - 'POSTGRES_USER=Cristian'
      - 'POSTGRES_PASSWORD=2242'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bus-network

volumes:
  postgres_data:
    driver: local

networks:
  bus-network:
    driver: bridge
